### ISSUE TITLE
Rendered site has incomplete/broken layout

### ISSUE THREAD

**Issue by marians** [apvarun/digital-garden-hugo-theme#10]
Hi! Based on the demo I saw I liked this theme a lot and gave it a try, but couldn't make it work. Here is what I tried to use exactly what's in the example site:

```
mkdir hugo-test
cd hugo-test/
hugo new site mysite
cd mysite
git clone https://github.com/apvarun/digital-garden-hugo-theme.git themes/digitalgarden
cp -r themes/digitalgarden/exampleSite/* .
cp themes/digitalgarden/package* .
nvm use 16.12.0
npm install
npm i -g postcss-cli
npm run build
npm run dev
```

The result looks like this both in Firefox and Chrome:

<img width="1362" alt="grafik" src="https://user-images.githubusercontent.com/273727/180298381-c875c214-54cb-4f1e-bf70-fc14311c515c.png">

I'm doing this on MacOS with hugo v0.101.0 and NodeJS version 16.12.0. Any idea what could be the problem?

**Comment by marians** [comment]
The generated `static/css/main.css` file looks very different from the one at https://digital-garden-hugo-theme.vercel.app/css/main.css

Here it is:

```css
/*! tailwindcss v3.0.6 | MIT License | https://tailwindcss.com*/*,:after,:before{box-sizing:border-box;border:0 solid}:after,:before{--tw-content:""}html{line-height:1.5;-webkit-text-size-adjust:100%;-moz-tab-size:4;-o-tab-size:4;tab-size:4;font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}body{margin:0;line-height:inherit}hr{height:0;color:inherit;border-top-width:1px}abbr[title]{-webkit-text-decoration:underline dotted;text-decoration:underline dotted}h1,h2,h3,h4,h5,h6{font-size:inherit;font-weight:inherit}a{color:inherit;text-decoration:inherit}b,strong{font-weight:bolder}code,kbd,pre,samp{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace;font-size:1em}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:initial}sub{bottom:-.25em}sup{top:-.5em}table{text-indent:0;border-color:inherit;border-collapse:collapse}button,input,optgroup,select,textarea{font-family:inherit;font-size:100%;line-height:inherit;color:inherit;margin:0;padding:0}button,select{text-transform:none}[type=button],[type=reset],[type=submit],button{-webkit-appearance:button;background-color:initial;background-image:none}:-moz-focusring{outline:auto}:-moz-ui-invalid{box-shadow:none}progress{vertical-align:initial}::-webkit-inner-spin-button,::-webkit-outer-spin-button{height:auto}[type=search]{-webkit-appearance:textfield;outline-offset:-2px}::-webkit-search-decoration{-webkit-appearance:none}::-webkit-file-upload-button{-webkit-appearance:button;font:inherit}summary{display:list-item}blockquote,dd,dl,figure,h1,h2,h3,h4,h5,h6,hr,p,pre{margin:0}fieldset{margin:0}fieldset,legend{padding:0}menu,ol,ul{list-style:none;margin:0;padding:0}textarea{resize:vertical}input::-moz-placeholder,textarea::-moz-placeholder{opacity:1;color:#9ca3af}input:-ms-input-placeholder,textarea:-ms-input-placeholder{opacity:1;color:#9ca3af}input::placeholder,textarea::placeholder{opacity:1;color:#9ca3af}[role=button],button{cursor:pointer}:disabled{cursor:default}audio,canvas,embed,iframe,img,object,svg,video{display:block;vertical-align:middle}img,video{max-width:100%;height:auto}[hidden]{display:none}body{--tw-text-opacity:1;color:rgb(15 23 42/var(--tw-text-opacity))}@media (prefers-color-scheme:dark){body{--tw-bg-opacity:1;background-color:rgb(15 23 42/var(--tw-bg-opacity));--tw-text-opacity:1;color:rgb(248 250 252/var(--tw-text-opacity))}body ::-moz-selection{--tw-bg-opacity:1;background-color:rgb(71 85 105/var(--tw-bg-opacity))}body ::selection{--tw-bg-opacity:1;background-color:rgb(71 85 105/var(--tw-bg-opacity))}body::-moz-selection{--tw-bg-opacity:1;background-color:rgb(71 85 105/var(--tw-bg-opacity))}body::selection{--tw-bg-opacity:1;background-color:rgb(71 85 105/var(--tw-bg-opacity))}}*{scrollbar-width:thin;scrollbar-color:#94a3b8 #e2e8f0}::-webkit-scrollbar{width:8px}::-webkit-scrollbar-track{--tw-bg-opacity:1;background-color:rgb(226 232 240/var(--tw-bg-opacity))}::-webkit-scrollbar-thumb{--tw-bg-opacity:1;background-color:rgb(148 163 184/var(--tw-bg-opacity));border-radius:6px}html.dark ::-webkit-scrollbar-track{--tw-bg-opacity:1;background-color:rgb(71 85 105/var(--tw-bg-opacity))}html.dark ::-webkit-scrollbar-thumb{--tw-bg-opacity:1;background-color:rgb(148 163 184/var(--tw-bg-opacity))}html.dark *{scrollbar-color:#94a3b8 #475569}
```

When I overwrite my `main.css` with the content from https://digital-garden-hugo-theme.vercel.app/css/main.css , everything looks fine.
